### ISSUE TITLE
Incorrect annotations

### ISSUE THREAD

**Issue by sinaahmadi** [unimorph/ckb#1]
Hi,
Thanks for the great project!
Unfortuantely this dataset is full of errors not only in writing, but also in declining word forms. Word forms seem to be taken from the Alexina project where a phonemic approach was used for transcribing words, as in `bestbwwn` instead of `bestibûm` or `بەستبووم`. This poses problem as there is no external resource for Kurdish using that writing (therefore not making the annotations much useful). On the other hand, the annotations seem to be done with Southern Kurdish morphology in mind instead of Central Kurdish as in `bbestynbayě` or `šelybwwnbayě` which don't mean anything!

I thought I should raise this issue as I see it is included in the last verison of Unimorph, a bit precipitously. 
I'll be happy to help out with correcting the errors.

**Comment by ivri** [comment]
Dear Sina, apologies for such a late reply, I just noticed the issue. How difficult would it be to fix the writing? Is there any existing tool we could use? Or does it make the current data useless, and we should seek for another data sources?

**Comment by sinaahmadi** [comment]
Hi @ivri ,
Glad you could get back to this. Thanks :-)
I guess correcting the current forms will take more time than annotating new ones using the available analyzers following a manual verification. I have this analyzer that can be used to check the existing annotations: https://github.com/sinaahmadi/KurdishHunspell (used in https://github.com/sinaahmadi/klpt).

I’d say that a better solution would be to use the less problematic word forms in the current dataset, which happen to be nouns, along with new forms extracted from corpora. Collecting data should not be an issue given that there are many corpora available for Sorani.

Do you have any preference regarding the number/distribution of forms?

**Comment by ivri** [comment]
We don not have any preferences regarding the number and distribution of forms, the more the better (and also in terms of the paradigm coverage). We can try fixing the data we have (or at least the most straightforward cases), reducing the noise. If it's possible, would be great to have a cleaner and richer dataset (you may push your own data as an extra file)
